<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Models\Airline;
use App\Services\AdminAnalyticsService;
use App\Support\PaymentMethodCatalog;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AdminReportController extends Controller
{
    public function __construct(
        protected AdminAnalyticsService $analyticsService
    ) {
    }

    public function index(Request $request)
    {
        $filters = [
            'date_from' => $request->string('date_from')->toString(),
            'date_to' => $request->string('date_to')->toString(),
            'airline_id' => $request->integer('airline_id'),
            'route' => $request->string('route')->toString(),
            'payment_status' => $request->string('payment_status')->toString(),
            'booking_status' => $request->string('booking_status')->toString(),
        ];

        $summary = $this->analyticsService->reportSummary($filters);
        $reportData = $this->analyticsService->reportExportData($filters);
        $airlines = Airline::query()->orderBy('name')->get(['id', 'name']);

        if ($request->string('export')->toString() === 'csv') {
            return $this->exportCsv(
                $filters,
                $summary,
                $reportData,
                $airlines->keyBy('id')->all(),
            );
        }

        return view('admin.reports.index', compact('summary', 'filters', 'airlines', 'reportData'));
    }

    protected function exportCsv(array $filters, array $summary, array $exportData, array $airlines): StreamedResponse
    {
        $filename = 'admin-report-'.now()->format('Ymd-His').'.csv';
        $reportId = 'ZNR-RPT-'.now()->format('YmdHis');

        return response()->streamDownload(function () use ($filters, $summary, $exportData, $airlines, $reportId) {
            $handle = fopen('php://output', 'w');
            fwrite($handle, "\xEF\xBB\xBF");

            fputcsv($handle, ['ZANNORA AIRLINE - OPERATION REPORT']);
            fputcsv($handle, ['Report ID', $reportId]);
            fputcsv($handle, ['Generated At', now()->format('d-m-Y H:i:s')]);
            fputcsv($handle, ['Generated By', optional(auth()->user())->name ?: 'System']);
            fputcsv($handle, ['Template Version', '2.0']);
            fputcsv($handle, []);
            fputcsv($handle, ['===== FILTER SUMMARY =====']);
            fputcsv($handle, ['Tanggal Dari', $filters['date_from'] ?: 'Semua tanggal']);
            fputcsv($handle, ['Tanggal Sampai', $filters['date_to'] ?: 'Semua tanggal']);
            fputcsv($handle, ['Airline', $filters['airline_id'] && isset($airlines[$filters['airline_id']]) ? $airlines[$filters['airline_id']]->name : 'Semua airline']);
            fputcsv($handle, ['Rute', $filters['route'] ?: 'Semua rute']);
            fputcsv($handle, ['Status Payment', $filters['payment_status'] ?: 'Semua status']);
            fputcsv($handle, ['Status Booking', $filters['booking_status'] ?: 'Semua status']);
            fputcsv($handle, []);
            fputcsv($handle, ['===== KPI SUMMARY =====']);
            fputcsv($handle, ['Metric', 'Value']);
            fputcsv($handle, ['Total Bookings', $summary['total_bookings']]);
            fputcsv($handle, ['Payment Paid', $summary['total_paid_payments']]);
            fputcsv($handle, ['Booking Cancelled', $summary['total_cancelled_bookings']]);
            fputcsv($handle, ['Flight Aktif', $summary['total_active_flights']]);
            fputcsv($handle, ['Pendapatan Total', $this->currency((float) $summary['revenue_total'])]);
            fputcsv($handle, []);
            fputcsv($handle, ['===== BOOKING STATUS BREAKDOWN =====']);
            fputcsv($handle, ['Status', 'Total']);

            foreach ($exportData['booking_status_breakdown'] as $status => $total) {
                fputcsv($handle, [ucfirst((string) $status), $total]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== PAYMENT STATUS BREAKDOWN =====']);
            fputcsv($handle, ['Status', 'Total']);

            foreach ($exportData['payment_status_breakdown'] as $status => $total) {
                fputcsv($handle, [ucfirst((string) $status), $total]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== PAYMENT METHOD BREAKDOWN =====']);
            fputcsv($handle, ['Metode', 'Transaksi', 'Nominal']);

            foreach ($exportData['payment_method_breakdown'] as $item) {
                fputcsv($handle, [
                    PaymentMethodCatalog::label($item['payment_method']),
                    $item['total_transactions'],
                    $this->currency((float) $item['total_amount']),
                ]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== REVENUE PER MONTH =====']);
            fputcsv($handle, ['Bulan', 'Nominal']);

            foreach ($summary['monthly_revenue'] as $item) {
                fputcsv($handle, [
                    $item['month'],
                    $this->currency((float) $item['total']),
                ]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== POPULAR ROUTES =====']);
            fputcsv($handle, ['Rute', 'Nomor Flight', 'Total Booking']);

            foreach ($summary['popular_routes'] as $route) {
                fputcsv($handle, [
                    $route['route'],
                    $route['flight_number'],
                    $route['total_bookings'],
                ]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== BOOKING DETAIL TABLE =====']);
            fputcsv($handle, [
                'Kode Booking',
                'Waktu Booking',
                'Nama User',
                'Email User',
                'Airline',
                'Nomor Flight',
                'Rute',
                'Jumlah Passenger',
                'Status Booking',
                'Status Payment',
                'Metode Payment',
                'Waktu Paid',
                'Total Harga',
                'Expired At',
            ]);

            foreach ($exportData['booking_rows'] as $row) {
                fputcsv($handle, [
                    $row['booking_code'],
                    $row['booked_at'],
                    $row['user_name'],
                    $row['user_email'],
                    $row['airline'],
                    $row['flight_number'],
                    $row['route'],
                    $row['passengers'],
                    ucfirst($row['booking_status']),
                    ucfirst($row['payment_status']),
                    PaymentMethodCatalog::label($row['payment_method']),
                    $row['paid_at'] ?: '-',
                    $this->currency((float) $row['total_price']),
                    $row['expired_at'] ?: '-',
                ]);
            }

            fputcsv($handle, []);
            fputcsv($handle, ['===== END OF REPORT =====']);
            fputcsv($handle, ['Generated by Cakrawala Admin Panel']);

            fclose($handle);
        }, $filename);
    }

    protected function currency(float $amount): string
    {
        return 'Rp'.number_format($amount, 0, ',', '.');
    }
}
